# Generated by Django 3.2.3 on 2021-05-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectname', verbose_name='Project:'),
        ),
    ]
