# Generated by Django 3.2.3 on 2021-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmonth',
            name='project_month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
