# Generated by Django 3.2.3 on 2021-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210518_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmonth',
            name='project_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='project_name',
            field=models.CharField(max_length=30),
        ),
    ]
