# Generated by Django 3.2.3 on 2021-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210518_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pspent', models.CharField(max_length=30, verbose_name='Project')),
                ('espent', models.CharField(max_length=30, verbose_name='Employee')),
                ('mspent', models.CharField(max_length=30, verbose_name='Month')),
                ('tspent', models.DurationField(verbose_name='Total Hour Spent:')),
            ],
        ),
        migrations.AlterField(
            model_name='projectmonth',
            name='project_month',
            field=models.CharField(max_length=30),
        ),
    ]
